package domain

type GameEventType string

const (
	EventGameStart       GameEventType = "game_start"
	EventMoveMade        GameEventType = "move_made"
	EventGameOver        GameEventType = "game_over"
	EventSpectatorJoined GameEventType = "spectator_joined"
	EventQueueJoined     GameEventType = "queue_joined"
	EventQueueLeft       GameEventType = "queue_left"
	EventError           GameEventType = "error"
	EventInfo            GameEventType = "info"
)

// GameEvent represents an event generated by the game logic
// to be consumed by the transport layer (WebSocket)
type GameEvent struct {
	Type       GameEventType
	Recipients []int64     // UserIDs to send this event to
	Payload    interface{} // The actual message payload (usually ServerMessage)
}
